# Name of the domain bridge, used for node naming and logging
name: multiple_robots_bridge
from_domain: 0
to_domain: 1

topics:
  clock:
    type: clock
  joint_states:
    type: joint_states
  imu:
    type: imu/data_raw
  camera_proc:
    type: camera/image_proc
  camera_info:
    type: camera/camera_info

  
  command:
    type: DynamixelController/command
    # Reverse 'from' and 'to' domains (bridge from domain ID 3 to domain ID 2)
    reversed: True


